name: Enhancement Request
description: Suggest an enhancement or improvement for the project.
title: "[Enhancement] "
labels: 
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        ### **Description**
        A clear and concise description of the feature or improvement you'd like to request.

  - type: input
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the feature or improvement.
      placeholder: A clear and concise description of the feature or improvement you'd like to request.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### **Why Is This Enhancement Needed?**
        Explain why this enhancement is important or beneficial.

  - type: textarea
    id: why_needed
    attributes:
      label: Why Is This Enhancement Needed?
      description: Explain the importance or benefit of this enhancement.
      placeholder: Explain why this enhancement is important or beneficial.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### **Proposed Solution**
        Describe the proposed solution or feature in detail.

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: Describe the proposed solution or feature in detail.
      placeholder: Provide a detailed description of the proposed solution or feature.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### **Additional Context**
        Add any other context or screenshots about the enhancement request here.

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Provide any additional context or relevant information.
      placeholder: Add any other relevant information or context here.
    validations:
      required: false
