name: Package Upgrade
description: Request to upgrade a dependency or package.
title: "[Upgrade] "
labels: 
  - upgrade
body:
  - type: markdown
    attributes:
      value: |
        ### **Package to Upgrade**
        Specify the package and versions involved in the upgrade.

  - type: input
    id: package_name
    attributes:
      label: Package Name
      description: Provide the name of the package to upgrade.
      placeholder: e.g., OpenCV
    validations:
      required: true

  - type: input
    id: current_version
    attributes:
      label: Current Version
      description: Specify the current version of the package.
      placeholder: e.g., v4.9.0
    validations:
      required: true

  - type: input
    id: new_version
    attributes:
      label: New Version
      description: Specify the new version of the package.
      placeholder: e.g., v4.10.0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### **Reason for Upgrade**
        Provide a reason for upgrading the package (e.g., new features, bug fixes, security patches).

  - type: textarea
    id: reason
    attributes:
      label: Reason for Upgrade
      description: Describe the rationale for the upgrade.
      placeholder: Provide a reason for upgrading the package.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### **Potential Risks**
        Outline any potential risks or issues associated with the upgrade (e.g., breaking changes, compatibility issues).

  - type: textarea
    id: risks
    attributes:
      label: Potential Risks
      description: Describe any risks associated with the upgrade.
      placeholder: Outline potential risks or issues related to the upgrade.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### **Testing**
        Describe how the upgrade will be tested to ensure it doesn’t break anything.

  - type: textarea
    id: testing
    attributes:
      label: Testing Plan
      description: Describe how the upgrade will be verified.
      placeholder: Provide the steps or plan for testing the package upgrade.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### **Additional Context**
        Add any other relevant context or links to release notes/changelogs.

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Provide any additional context, such as links to release notes or changelogs.
      placeholder: Add any relevant context or links.
    validations:
      required: false
