name: Unit and Integration Tests

on:
  pull_request:
    branches: ["development"]
  push:
    branches: ["development"]
  workflow_dispatch:

jobs:
  build-and-test-x64:
    strategy:
      fail-fast: false
      matrix:
        type: [Unit, Integration]

    concurrency:
      group: "tests-x64-${{ matrix.type }}"
      cancel-in-progress: false

    runs-on: [self-hosted, linux, X64]

    steps:
      - name: Setup Action Environment
        if: always()
        run: |
          cd /opt
          if [ ! -d "Autonomy_Software" ]; then git clone --recurse-submodules -j8 https://github.com/MissouriMRDT/Autonomy_Software.git; fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fix Dubious Ownership
        run: git config --global --add safe.directory /opt/Autonomy_Software

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Update Branch
        run: |
          cd /opt/Autonomy_Software/
          git fetch --force --recurse-submodules
          branch=${{ steps.extract_branch.outputs.branch }}
          git reset --hard origin/$branch
          git checkout $branch
          git pull --ff-only
          git submodule update --force --recursive --init
          git config --global --add safe.directory /opt/Autonomy_Software/external

      - name: Build and Run Tests with CTest
        run: |
          DIRECTORY="/opt/Autonomy_Software/tests/${{ matrix.type }}/src"
          if [ ! -d "$DIRECTORY" ]; then
            echo "No ${{ matrix.type }} tests found. Skipping."
            exit 0
          fi

          cd /opt/Autonomy_Software/
          rm -rf build && mkdir build && cd build
          cmake -DBUILD_TESTS_MODE=ON ..
          make -j$(nproc)

          LABEL="${{ matrix.type == 'Unit' && 'UTest' || 'ITest' }}"
          ctest --output-on-failure -T Test -L "$LABEL" --output-junit "${LABEL}s.xml"

      - name: Cleanup Action Environment
        if: always()
        run: rm -rf /opt/Autonomy_Software

  build-and-test-arm64:
    strategy:
      fail-fast: false
      matrix:
        type: [Unit, Integration]

    concurrency:
      group: "tests-arm64-${{ matrix.type }}"
      cancel-in-progress: false

    runs-on: [self-hosted, linux, ARM64]

    steps:
      - name: Setup Action Environment
        if: always()
        run: |
          cd /opt
          if [ ! -d "Autonomy_Software" ]; then git clone --recurse-submodules -j8 https://github.com/MissouriMRDT/Autonomy_Software.git; fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fix Dubious Ownership
        run: git config --global --add safe.directory /opt/Autonomy_Software

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Update Branch
        run: |
          cd /opt/Autonomy_Software/
          git fetch --force --recurse-submodules
          branch=${{ steps.extract_branch.outputs.branch }}
          git reset --hard origin/$branch
          git checkout $branch
          git pull --ff-only
          git submodule update --force --recursive --init
          git config --global --add safe.directory /opt/Autonomy_Software/external

      - name: Build and Run Tests with CTest
        run: |
          DIRECTORY="/opt/Autonomy_Software/tests/${{ matrix.type }}/src"
          if [ ! -d "$DIRECTORY" ]; then
            echo "No ${{ matrix.type }} tests found. Skipping."
            exit 0
          fi

          cd /opt/Autonomy_Software/
          rm -rf build && mkdir build && cd build
          cmake -DBUILD_TESTS_MODE=ON ..
          make -j$(nproc)

          LABEL="${{ matrix.type == 'Unit' && 'UTest' || 'ITest' }}"
          ctest --output-on-failure -T Test -L "$LABEL" --output-junit "${LABEL}s.xml"

      - name: Cleanup Action Environment
        if: always()
        run: rm -rf /opt/Autonomy_Software
